version: '2'

services:
  app:
    image: golang:1.18.3
    volumes:
      - .:/work
    working_dir: /work

  licensing:
    build:
      context: ./docker
      dockerfile: Dockerfile.licensed
    volumes:
      - .:/work
    working_dir: /work
